### ISSUE TITLE
Remove / replace unnecessary binary ZIP files

### ISSUE THREAD

**Issue by Chefkoch81** [siemens/CtrlppCheck#19]
The ZIP file for third party license information provided in #18 breaks compareability due to being binary.

If there is no particular reason for that, beside it has always been done that way, this needs to be committed in a human readable format instead of ZIP. Best would be text only or markdown.

With having binary files in the repo, we could consider adding lfs support, but I would rather avoid that if is only for non-reasons.

**Comment by dhoegerlETM** [comment]
Agreed with Thomas to extract the ZIP directly to an own docu-folder to not interpret/invalidate the required content.
