### ISSUE TITLE
Please add Visual Studio Code extension

### ISSUE THREAD

**Issue by hfrmobile** [siemens/CtrlppCheck#31]
**Is your feature request related to a problem? Please describe.**
No, but using Visual Studio code

**Describe the solution you'd like**
CtrlppCheck checks should be done Visual Studio Code automatically when .ctl file is opened.

**Describe alternatives you've considered**
Calling CtrlppCheck executable within Visual Studio Code.

**Comment by dhoegerlETM** [comment]
Please check out the existing VS Code plugin under:
https://marketplace.visualstudio.com/items?itemName=SloopTools.ctrlpptools&utm_source=VSCode.pro&utm_campaign=AhmadAwais
