### ISSUE TITLE
First time user confusion

### ISSUE THREAD

**Issue by cbv08** [siemens/CtrlppCheck#48]
Hello,

This is not really a bug, but a comment on the documentation.

I wanted to use CtrlppCheck so I cloned the repo onto my machine and tried following the user documentation.

However I quickly got stuck on: 
"4. Put the ctrlppcheck binary in a folder called "ctrlppcheck" in the bin folder of the WinCCOA_QualityChecks subproject. (If you want to put it in a different folder you must add the path to it to the config file: [qualityChecks] ctrlppcheckPath="yourpathtobinary")"

As i could not find a binary file. Not within the Repo and also not anywhere else i looked. At some point i realized I could build the project myself I installed Cmake and Visual studio and created the binary file.

After this I discovered the contributer.md document describing how to do this. I didn't look in there as i do not consider myself a contributer but a user. 

Perhaps I have overlooked the binary file. But then a link to where it can be found would be super helpful for first time users. If I was supposed to build it, as a user then a simple link to the contributer.md documentation would go a long way.

Kind regards 
Olav

**Comment by andygruber** [comment]
@cbv08 Hi,

Sry for the the inconveniance, the ready to use package can be found directly here on GitHub in the assets of the releases:
https://github.com/siemens/CtrlppCheck/releases

Checkout [WinCCOA_QualityChecks_v1.0.1.zip](https://github.com/siemens/CtrlppCheck/releases/download/v1.0.1/WinCCOA_QualityChecks_v1.0.1.zip), which is the current stable version, or the prerelease [WinCCOA_QualityChecks_v1.0.2.zip](https://github.com/siemens/CtrlppCheck/releases/download/v1.0.2/WinCCOA_QualityChecks_v1.0.2.zip) .

I hope that answers your question and I will keep that open to check how the documentation can be improved.

BR, Andreas

**Comment by cbv08** [comment]
Hahaha that is a much easier way to do it than I did. Thank you for that! I am not used to the github user interface, so i completely missed the release section on the right hand side. Though this way point 4 is obsolete as the binary is already in the folder.

Again thank you for the response!

Kind regards 
Olav

**Comment by cbv08** [comment]
@andygruber do you know if there is some kind of forum for questions and the likes. Or is this the place I should use? I am having some odd issues that I am not entirely sure how to proceed.

Kind regards
Olav

**Comment by dhoegerlETM** [comment]
@cbv08 the **_issues_** section should be used for reporting findings or proposing new features.

Please use the **_discussion_** section as a forum to ask questions or discuss topics:
https://github.com/siemens/CtrlppCheck/discussions
