### ISSUE TITLE
Spurious error messages

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#49]
**Describe the bug**
After each usage, three lines get appended to the “Problems” list, that on the first sight don’t make lots of sense:

-  There is no rule to execute. Tokenlist raw – ruleCheck_noRule
-  There is no rule to execute. Tokenlist normal – ruleCheck_noRule
-  There is no rule to execute. Tokenlist simple – ruleCheck noRule

If in some library/script no mistakes whatsoever is found, the programs still indicates these three. That's a little confusing.

**To Reproduce**
1. Open a library/script
2. Click on 'Ctrlpp Check'
3. Open the 'Errors' subpanel

**Expected behavior**
Theses lines are a little confusing and should not appear at all.

**Comment by dhoegerlETM** [comment]
Not reproducible. Please check your correct usage and configuration according to our tool documentation -> register project WinCCOA_QualityChecks and add it as subproject to your running project, then import the dplist WinCCOA_QualityChecks.dpl from that subproject using ASCII manager. Only afterwards you are set up correctly and can use the checker.

**Comment by cbv08** [comment]
Hello

I also get this problem, only when using version 1.0.1 
I don't get it when using pre release version 1.0.2

kind regards 
Olav
