### ISSUE TITLE
Conditional operator falsely evaluated

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#51]
**Describe the bug**
The program apparently does not deal well with the conditional operator. It gets falsely identified with a loop, when it comes to identify these segments of code that may be called more than necessary. When a function is given to this operator (exp ? fct1 : fct2), this gets evaluated as a “non-performing usage of a function in a loop” performing error in the panel.

**To Reproduce**
1. Open any library/script that contains a conditional operator with functions as arguments.
2. Launch Ctrlpp Check
3. Open the "Performance issues" subpanel.

**Expected behavior**
A function call within a conditional operator is perfectly legitimate and should not be interpreted as a performance issue by the program.

**Comment by dhoegerlETM** [comment]
Not reproducible with version 1.0.2 and default settings.
