### ISSUE TITLE
Delays () not identified

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#53]
**Describe the bug**

The program identifies delay () functions as handicaps to performance when they get called inside of loops. In practice it is not really the case, because you would not put a delay in a loop if you don’t need it. 

**To Reproduce**
1. Open any script/library with a delay() function call in the body of a loop.
2. Run Ctrlpp Check.
3. Click on the "Performance Issues" tab.
4. An error message with the line corresponding to the delay() function call is present. 

**Expected behavior**
An exception should be made for delay() calls in this case. Instead of being understood as a performance issue by the program, it should probably be only a warning or something benign.

**Comment by dhoegerlETM** [comment]
Evaluating such finding (or similar) as warning/error is a matter of your settings. You may always decide to ignore it or lower its priority.
