### ISSUE TITLE
Variable falsely assumed to be unused

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#55]
**Describe the bug**
When a variable gets initialized with some value that is later evaluated, but not assigned, the program falsely claim that the variable is not used.

**To Reproduce**
1. Open any script/library where a variable gets initialized but not assigned to any other variable. The variable in question should be matched against some hard-coded value or another variable within a conditional statement.
2. Run Ctrlpp Check.
3. Check the "Errors" subpanel.
4. A warning is to be seen concerning the variable with the mention: "unused variable".

**Expected behavior**
No warning should be issued in this case. It is perfectly fine to declare a variable only in order to store some value that is never assigned, but only evaluated.

**Comment by dhoegerlETM** [comment]
Duplicate with #5
