### ISSUE TITLE
False performance issue

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#56]
**Bug Description**

Functions get rightfully called within a loop when they make use of the iterator as an argument. In such cases, their presence within the body of a loop shouldn’t be at the origin of an error message concerning performance. Nevertheless, it does. The program seems to label any function call within a loop a performance issue, even when the iterator is needed within the argument list.

**To Reproduce**
1. Open any library/script where some function is called within the body of a loop. This function should make use of the corresponding iterator in its argument list.
2. Run Ctrlpp Check.
3. Click on the "performance issue" tab.
4. An error/warning appear for the line corresponding to the function call. The call is falsely labeled as a performance issue.

**Expected behavior**
There are plenty of cases where a function should be called within the body of a loop. Provided that at least an argument of the function is the iterator or makes use of the iterator, this should not be labeled a performance issue.

**Comment by dhoegerlETM** [comment]
Not reproducible with version 1.0.2
