### ISSUE TITLE
Errors numbering

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#57]
**Describe the bug**

In the error panel, the number of categories of errors gets printed. It would surely make more sense to print the total number of errors.

**To Reproduce**
1. Open any library/script with some repeated coding style/performance/argument count errors within it.
2. Run Ctrlpp Check for this library/script.
3. Check the number of errors shown on the "error" tab. Click on this tab.
4. Within the panel referencing every errors, compare the actual amount of line with preceding number.

**Expected behavior**
The number of error found should correspond to the actual number of lines within the list, not to the number of different categories of errors. This last information is of little value.

**Comment by dhoegerlETM** [comment]
Works correctly in version 1.0.2. E.g. I have 6 lines in the list and the overview dashboard correctly shows 2 "errors & warnings" and 4 "style & information".
