### ISSUE TITLE
Include files

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#58]
**Describe the bug**

Ctrlcpp Check cannot always find the included files, even when they are to be found in a close location. That could be very problematic in the sense that whole arrays of error messages may be produced for no good reason. In particular, the constants defined in other files do not get resolved by the program.

**To Reproduce**
1. Open any library/script that makes use of the #uses directive.
2. Run Ctrlpp Check for that library/script.
3. Click on the Errors tab.
4. Some error messages describe an "unresolved dependencies" issues.

**Expected behavior**
The program should be able to read the files joined through the "#uses" directive. Constants belonging to these files should not be denounced as "undefined variable" in dedicated error messages. This is a big problem because the output of Ctrlpp Check may become entirely cluttered by these false warnings/errors and it gets really difficult to dissociate real issues from these ones.

**Comment by dhoegerlETM** [comment]
Duplicate with #4
