### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#59]
**Describe the bug**

When several “undefined variables” are somehow present in the same line of code, only one gets acknowledged as an error.

**To Reproduce**
1. Open any library/script. One line of the chosen file should contain several call to undefined variables.
2. Run Ctrlpp Check for this particular file.
3. Check the error tab.
4. Only one error gets reported for the concerned line.

**Expected behavior**
A warning should be given under the form of a dedicated error line in the corresponding panel of Ctrlpp Check for every undefined variable. In the other case, one would be forced to restart the program several time and correct one error after the other.

**Comment by dhoegerlETM** [comment]
Not reproducible with version 1.0.2
