### ISSUE TITLE
Optional nature of arguments not recognized

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#60]
**Describe the bug**

When a function with six possible parameters, two of which being optional, is called with the four obligatory only, Ctrlpp Check interprets it as an “checkLibraryFunctionArgCount” error.

**To Reproduce**
1. Open any library/script that includes a call to a function where the optional parameter are omitted.
2. Run Ctrlpp Check for that script/library.
3. In the error panels, a warning appear under the "checkLibraryFunctionArgCount" category.

**Expected behavior**
In this case, there should be no warning.

**Comment by dhoegerlETM** [comment]
Not reproducible with version 1.0.2
