### ISSUE TITLE
Language incoherences

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#62]
**Describe the bug**
The titles of the different columns in the panel are written in German, whereas the error messages appear in English.

**To Reproduce**
1. Open any script/library with an error.
2. Run Ctrlpp Check on that library/script.
3. Look at the panel. Columns are written in the first language chosen on WinCC OA, whereas the error messages are in English.

**Expected behavior**
Language should be uniform.

**Comment by dhoegerlETM** [comment]
Those message are coming from cppcheck base and therefore cannot be handled via WinCC OA catalog files. That is by design.
