### ISSUE TITLE
Const dyn_int

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#63]
**Describe the bug**
The program either does not recognize the ability to make local array const, or it does print the false error message, when the contents of the dyn_int are constants that are defined in another file, that it cannot link.

**To Reproduce**
1. Open any library/script. Define a const dyn_int and a dyn_int with constants within it, that are declared in another file.
2. Run Ctrlpp Check
3. Click on the Error Tab. There will be two warning. in the first case because of the const qualifier, in the second case because of the unrecognized constants.

**Expected behavior**
Defining a dyn_int as const should be allowed.
If a constant goes unrecognized by the program and belongs to a dyn_int, the warning message should be very clear about the real cause of the error and distinct from the first case (const dyn_int).

**Comment by dhoegerlETM** [comment]
Duplicate with #5
