### ISSUE TITLE
Library Check

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#68]
**Describe the bug**
A severe error message makes its appearance (Operation not permitted with these arguments).

**To Reproduce**
1. Choose a random library and perform the test from CtrlCpp Check GUI (not from the script editor).

**Expected behavior**
Running the test for a library from the GUI should be fine and certainly not be the cause of any error message.

**Comment by dhoegerlETM** [comment]
@mPokornyETM seems we introduced a regression here - I'm using most recent 1.0.2. No matter if I click "CtrlppCheck - whole project" or more specific "Libs check" I get the following log entry:

WCCOAui      (1), 2023.11.08 21:43:29.662, CTRL, INFO,       21/QgBase, Start quality gate QgCtrlppCheck.
WCCOAui      (1), 2023.11.08 21:43:29.686, CTRL, INFO,       22/QgBase, Calculate sources for quality gate QgCtrlppCheck.
WCCOAui      (1), 2023.11.08 21:43:29.929, CTRL, WARNING,    61, Cannot open file, 
    Module: WinCCOA_QualityChecks
    Panel: \WinCCOA_QualityChecks\panels\vision\QualityChecks\QG_History.pnl [WinCCOA - Quality checks results]
    Script: Initialize
    In panel scope library: \WinCCOA_QualityChecks\panels\vision\QualityChecks\QG_History.pnl
    Line: 22, fileToString, <proj>/data/QualityGates/QgStaticCheck_Libs/1699476111/Score, The system cannot find the file specified.

**Comment by mPokornyETM** [comment]
Please assign it to me. I will provide fix ASAP. Maybe a ctrl-click test will be good idea to eliminate this kind of regressions. Let me see.
