### ISSUE TITLE
Unregistered Projects

### ISSUE THREAD

**Issue by maxChevSOL** [siemens/CtrlppCheck#69]
**Describe the bug**
Only registered projects can be analyzed. This can be really annoying within a Pipeline (CI/CD) context.

**To Reproduce**
1. Try to analyze an unregistered project.

**Expected behavior**
The analyze of unregistered projects should be possible.

**Comment by jumoog** [comment]
You can call `ctrlppcheck` directly.

**Comment by dhoegerlETM** [comment]
See documentation of the command line usage:
https://github.com/siemens/CtrlppCheck/blob/main/docs/user.md#use-from-the-command-line
