### ISSUE TITLE
CtrlppCheck: resolve conversion between int/long and time

### ISSUE THREAD

**Issue by ghost** [siemens/CtrlppCheck#7]
**Describe the bug**
CTRL explicitly defines a valid conversion between int/long and time, because time is int64 internally. But
```
time tStartTime;
...
if (tStartTime != 0)
{
}
...
```
results in
![image](https://user-images.githubusercontent.com/114389675/207601361-d0f33524-d62c-4bde-8f44-c3151c88a25b.png)

**To Reproduce**
1. add code snipped above to a ctrl scripts in GEDI
2. Start "Ctrlppcheck" from within GEDI
3. Check results

**Expected behavior**
Ctrlppcheck correctly understands all conversions Ctrl implements

**Software version and environment (please complete the following information):**
 - WinCC OA Version: 3.19.0

**Comment by jumoog** [comment]
https://www.winccoa.com/documentation/WinCCOA/latest/en_US/Features/Features.html#misc_enhancements__d4444e93

> Avoid int <-> time conversions and vice versa. These must be changed to long <-> time conversions. CTRL outputs a warning as of the version 3.19.

**Comment by mPokornyETM** [comment]
As @jumoog  answer here, the behaviour is correct

You shall change your code like this

```
time tStartTime;
...
if (tStartTime != 0L)
{
}
...
```
And you will be safe for next 3*10^9 years.

**Comment by mPokornyETM** [comment]
@dhoegerlETM  I think, we can close this issue
