### ISSUE TITLE
Cannot open reports v1.0.2

### ISSUE THREAD

**Issue by cbv08** [siemens/CtrlppCheck#71]
**Describe the bug**
Using version 1.0.2 I can make the checks in WinCC OA using the e.g. CtrlppCheck however when i try to open the report i get an error and nothing out. It works fine with version 1.0.1

**To Reproduce**
See description

**Expected behavior**
It should be possible to open the reports using version 1.0.2

**Software version and environment (please complete the following information):**
 - OS: windows 10
 - WinCC OA Version: 3.19
 - Version: 1.0.2

**Comment by dhoegerlETM** [comment]
@mPokornyETM please consider by chance

**Comment by mPokornyETM** [comment]
@cbv08 thx for investigating. Can you provide fix (in a PR pls) It will be faster way for all of us.
ps: when you provide the fix, pls paste in the PR screenshot before (the bug) and after. Thx

And I will try to create some ctrl-clik tests to eliminate this kind of regressions
