### ISSUE TITLE
Warning Message after starting WinCCOA - Gedi

### ISSUE THREAD

**Issue by rglockETM** [siemens/CtrlppCheck#75]
I've included the "WinCCOA_QualityChecks" as a subproject to the WinCC OA 3.19 Demo Application and started the project.

Immediately after starting the Gedi   (WCCOAui -m gedi) the logviewer shows the following error:

WCCOAui      (1), 2023.11.08 15:43:15.346, CTRL, WARNING,   117, Library defined as #uses "var" does not exist. See script 
    Script: D:\Projekte\3.19\WinCCOA_QualityChecks\scripts\libs\classes\ErrorHdl\OaLogger.ctl
, Line 10

Tested with Release v1.0.2 on 8.11.2023

**Comment by mPokornyETM** [comment]
Mayby it will be fine start this tool to check the ctrl code here too ;-) I will provide it as atest and try to fix it, thx for reporting
