### ISSUE TITLE
Gedi -> Quality Checks -> Open Online Help (wrong URL)

### ISSUE THREAD

**Issue by rglockETM** [siemens/CtrlppCheck#77]
Currently https://www.winccoa.com/documentation/WinCCOA/3.18/en_US/index.html is opened, but it should be 

https://www.winccoa.com/documentation/WinCCOA/latest/en_US/index.html in order to keep it at the newest possible way

**Comment by dhoegerlETM** [comment]
@mPokornyETM please consider soon

**Comment by mPokornyETM** [comment]
I think it shall be not pointed to WinCC OA documentation, but to documentation in this repo.
I mean it makse no sense to open WinCC OA documentation form the panel.
Shall I changed it as proposed, or changed it to this repo?

**Comment by dhoegerlETM** [comment]
I agree, please refer to the CtrlppCheck docu instead, because in the user.md we anyway reference to the WinCC OA documentation.
