### ISSUE TITLE
Error messages on opening "Settings" on a newly created project

### ISSUE THREAD

**Issue by rglockETM** [siemens/CtrlppCheck#83]
**Describe the bug**
WCCOAui      (1), 2023.11.09 11:14:30.031, CTRL, SEVERE,    176, Uncaught exception in thread started at main: 
WCCOAui      (1), 2023.11.09 11:14:30.031, CTRL, SEVERE,     79, Index out of range, 
    Module: Vision_2
    Panel: D:\Projekte\3.19\WinCCOA_QualityChecks\panels\WinCCOA_QualityChecks\general\Settings.pnl [Settings]
    Object: 42 named: "limitsTree" of type: TREE
    Script: Initialize
    Line: 86, map.getAt()[getActiveLang()], 1
	Stacktrace:
	     1: void fillWithData() at [Module: Vision_2 Panel: WinCCOA_QualityChecks\general\Settings.pnl Object: limitsTree Script: Initialize]:86
	     2: void main() at [Module: Vision_2 Panel: WinCCOA_QualityChecks\general\Settings.pnl Object: limitsTree Script: Initialize]:4

**To Reproduce**
1.) Create a new WinCC OA 3.19 project
2.) Add the Subproject "WinCCOA_QualityChecks"
3.) Import "WinCCOA_QualityChecks.dpl"
4.) Start the new project and open the Gedi
5.) Press "Settings"-Button at the QualityChecks - dock window

**Expected behavior**
Opening of the settings panel without any errors in the log

**Screenshots**
not necessary

**Software version and environment (please complete the following information):**
 - OS: [e.g. Linux <Distribution> <Architecture> <Kernel>]
 - WinCC OA Version: 3.19
 - Version: v1.0.2

**Additional context**
n.a.

**Comment by dhoegerlETM** [comment]
@mPokornyETM can't you click "assign yourself" in the "assignees" section?

**Comment by mPokornyETM** [comment]
> @mPokornyETM can't you click "assign yourself" in the "assignees" section?

no, it is disabled for me (as all other actions too)
![image](https://github.com/siemens/CtrlppCheck/assets/89339813/d4325cea-6ab3-41e8-bb8c-b7d04d0f2295)

**Comment by mPokornyETM** [comment]
@rglockETM has you imported "WinCCOA_QualityChecks.dpl" before ?

**Comment by rglockETM** [comment]
Yes, dpl has been imported (initial description updated).

**Comment by mPokornyETM** [comment]
> Yes, dpl has been imported (initial description updated).

strange, on my side works. I will try to create the project in some clean scope. We will see

**Comment by esaprykin** [comment]
The problem is in the mapping in with key "description" presented other mapping with string keys ("de_AT.utf8" and "en_US.utf8").
getActiveLang() returns number of active language according to config file. 
eg:
langs = "de_DE.utf8"
langs = "en_US.utf8"
langs = "ru_RU.utf8"
lang = "ru_RU.utf8"
getActiveLang() returns 3
